spring:
  application:
    name: demo
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=demo_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: YourPassword123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

app:
  log:
    directory: ./logs
  cors:
    allowed-origins: http://localhost:3000,http://localhost:4200

logging:
  level:
    root: INFO
    com.maybank.demo: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
